#!/bin/bash

echo "Removing Animoji/Memoji stickers caches..."
rm -f /var/mobile/Library/Avatar/Stickers/*.png
rm -f /var/tmp/com.apple.messages/*.png

echo "Restarting processes..."
killall -9 AnimojiStickersExtension || true
killall -9 "Developer Stickers" || true
